FORMAT: 1A
HOST: http://localhost:8080/

# TKDO

TKDo is a simple API allowing CRUD operations on tasks.

## List Tasks [/tasks{?page,page_size}]

+ Parameters
    + page: 3 (number, optional) - page number to return, zero indexed
        + Default: 0
    + page_size: 25 (number, optional) - maximum number of objects to return
        + Default: 50

### List Tasks [GET]
Use to get a list of tasks.

+ Request (application/json; charset=utf-8)

+ Response 200 (application/json; charset=utf-8)
    + Attributes (array[Task])

## Create A Task [/tasks]

### Create A Task [POST]

+ Request (application/json; charset=utf-8)

    + Attributes (NewTask)

+ Response 201

## Working with a Task [/tasks/{id}]

+ Parameters

    + id: `60853a85-681d-4620-9677-946bbfdc8fbc` (string) - unique identifier of the task

### Get a Task [GET]

+ Request (application/json; charset=utf-8)

+ Response 200 (application/json; charset=utf-8)
    + Attributes (Task)

### Update a task [PUT]

+ Request (application/json; charset=utf-8)

+ Attributes (Task)

+ Response 200 (application/json; charset=utf-8)
    + Attributes (Task)

### Delete a task [DELETE]

  + Request (application/json; charset=utf-8)

  + Response 200 (application/json; charset=utf-8)
      + Attributes (Task)

## Task Search [/tasks/search{?name,type}]

+ Parameters
    + name: 'buy apples' (string, optional) - name of the task
    + type (enum, optional) - type of the task

### Task Search [GET]

+ Request (application/json; charset=utf-8)

+ Response 200 (application/json; charset=utf-8)
    + Attributes (array[Task])

# Data Structures

## NewTask

+ name: clean the gutters (string, required) - name of the task
- taskType (enum, required)
    - basic|recurring

## Task

+ id: `60853a85-681d-4620-9677-946bbfdc8fbc` (string) - unique identifier of the task
+ status: open (string, required) - status of the task
+ Include NewTask
