FORMAT: 1A
HOST: http://localhost:8080/

# TKDO

TKDo is a simple API allowing CRUD operations on tasks.

## Health Check [/hc]

### Get [GET]
No-op to say the server is up or not

+ Response 200

## User [/users]

### Create User [POST]
Creates a given user

+ Request (application/json; charset=utf-8)
    + Attributes (User)

+ Response 201 (application/json; charset=utf-8)
    + Attributes (User)

## List Tasks [/tasks{?page,page_size}]

+ Parameters
    + page: 3 (number, optional) - page number to return, zero indexed
        + Default: 0
    + page_size: 25 (number, optional) - maximum number of objects to return
        + Default: 50

### List Tasks [GET]
Use to get a list of tasks.

+ Request (application/json; charset=utf-8)
    + Header

            uid: 00000000-0000-0000-0000-000000000000

+ Response 200 (application/json; charset=utf-8)
    + Attributes (array[Task])

+ Response 401 (application/json; charset=utf-8)
    + Attributes (Error)

## Create A Task [/tasks]

### Create A Task [POST]

+ Request (application/json; charset=utf-8)
    + Header

            uid: 00000000-0000-0000-0000-000000000000

    + Attributes (NewTask)

+ Response 201

+ Response 401 (application/json; charset=utf-8)
    + Attributes (Error)

## Working with a Task [/tasks/{id}]

+ Parameters

    + id: `60853a85-681d-4620-9677-946bbfdc8fbc` (string) - unique identifier of the task

### Get a Task [GET]

+ Request (application/json; charset=utf-8)
    + Header

            uid: 00000000-0000-0000-0000-000000000000

+ Response 200 (application/json; charset=utf-8)
    + Attributes (Task)

+ Response 401 (application/json; charset=utf-8)
    + Attributes (Error)

### Update a task [PUT]

+ Request (application/json; charset=utf-8)
    + Header

            uid: 00000000-0000-0000-0000-000000000000

+ Attributes (Task)

+ Response 200 (application/json; charset=utf-8)
    + Attributes (Task)

+ Response 401 (application/json; charset=utf-8)
    + Attributes (Error)

### Delete a task [DELETE]

+ Request (application/json; charset=utf-8)
    + Header

            uid: 00000000-0000-0000-0000-000000000000

+ Response 200 (application/json; charset=utf-8)
    + Attributes (Task)

+ Response 401 (application/json; charset=utf-8)
    + Attributes (Error)

## Task Search [/tasks/search{?name,type}]

+ Parameters
    + name: 'buy apples' (string, optional) - name of the task
    + type (enum, optional) - type of the task

### Task Search [GET]

+ Request (application/json; charset=utf-8)
    + Header

            uid: 00000000-0000-0000-0000-000000000000

+ Response 200 (application/json; charset=utf-8)
    + Attributes (array[Task])

+ Response 401 (application/json; charset=utf-8)
    + Attributes (Error)

# Data Structures

## Error
+ msg: what went wrong (string, required) - A description of what the error is

## NewTask

+ name: clean the gutters (string, required) - name of the task
- taskType (enum, required)
    - basic|recurring

## Task

+ id: `60853a85-681d-4620-9677-946bbfdc8fbc` (string) - unique identifier of the task
+ status: open (string, required) - status of the task
+ Include NewTask

## NewUser

+ name: Pat Smith (string, required) - user's name
+ email: something@something.com (string, required) - email address for the user

## User

- id: `00000000-0000-0000-0000-000000000000`
+ Include NewUser
